version: '3.8'

services:
    web:
        build:
            context: .
            dockerfile: Dockerfile.prod
        command: sh -c "python manage.py collectstatic --no-input --clear & python manage.py makemigrations --noinput & python manage.py migrate --noinput & gunicorn main.wsgi:application --bind 0.0.0.0:8004"
        volumes:
            - static_volume:/home/vorwerk/web/staticfiles/
            - media_volume:/home/vorwerk/web/media/
        expose:
            - 8004
        env_file:
            - ./.env.prod
        depends_on:
            - db
        networks:
            - frontend
            - backend
    db:
        image: postgres:14.1-alpine
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        ports:
            - 5435:5432
        env_file:
            - ./.env.db.prod
        networks:
            - frontend
            - backend
networks:
  frontend:
   external: true
  backend:
   external: true
volumes:
    postgres_data:
    static_volume:
    media_volume:
