# Generated by Django 4.1.3 on 2023-02-16 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('cidade', models.CharField(max_length=30)),
                ('codigopostal', models.CharField(max_length=50)),
                ('coordenadas', models.CharField(max_length=50)),
            ],
        ),
    ]
