# Generated by Django 4.1.3 on 2023-02-20 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locais', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='local',
            name='enderecodois',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='local',
            name='enderecoum',
            field=models.CharField(default='', max_length=80),
            preserve_default=False,
        ),
    ]
