# Generated by Django 4.1.7 on 2023-03-02 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locais', '0002_local_enderecodois_local_enderecoum'),
    ]

    operations = [
        migrations.AddField(
            model_name='local',
            name='latitude',
            field=models.CharField(default=' ', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='local',
            name='longitude',
            field=models.CharField(default=' ', max_length=50),
            preserve_default=False,
        ),
    ]
