# Generated by Django 4.1.3 on 2023-02-20 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subevento',
            name='notas',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
    ]
