# Generated by Django 4.1.7 on 2023-03-02 11:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eventos', '0002_alter_subevento_notas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MsgId', models.CharField(max_length=255)),
                ('From', models.CharField(max_length=255)),
                ('To', models.CharField(max_length=255)),
                ('Prefix', models.CharField(max_length=255)),
                ('Msg', models.CharField(max_length=255)),
                ('MCC', models.CharField(max_length=255)),
                ('MNC', models.CharField(max_length=255)),
                ('ReceivedDatetime', models.DateTimeField()),
                ('SegmentsTotalNumber', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='StoreCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5, unique=True)),
                ('is_redeemed', models.BooleanField(default=False)),
                ('picked', models.BooleanField(default=False)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='codes', to='eventos.evento')),
            ],
        ),
        migrations.CreateModel(
            name='BBCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=7, unique=True)),
                ('store_code', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bbcode', to='eventos.storecode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
