# Generated by Django 4.1.7 on 2023-03-03 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0003_message_storecode_bbcode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='MCC',
            new_name='mcc',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='MNC',
            new_name='mnc',
        ),
        migrations.AddField(
            model_name='bbcode',
            name='valid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='ReceivedDatetime',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='storecode',
            name='code',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
