# Generated by Django 4.1.7 on 2023-03-06 16:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eventos', '0004_rename_mcc_message_mcc_rename_mnc_message_mnc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward_type', models.CharField(choices=[('Reward 1', 1), ('Reward 2', 2), ('Reward 3', 3), ('Reward 4', 4), ('Reward 5', 5)], max_length=20)),
                ('bbcode', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reward', to='eventos.bbcode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
