# Generated by Django 4.1.7 on 2023-03-02 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locais', '0004_bimby'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='about',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='cidade',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='codigopostal',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
        migrations.AddField(
            model_name='profile',
            name='aceito',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='first_name',
            field=models.CharField(default=' ', max_length=80),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_name',
            field=models.CharField(default=' ', max_length=80),
        ),
        migrations.AddField(
            model_name='profile',
            name='loja',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='locais.local'),
            preserve_default=False,
        ),
    ]
