# Generated by Django 4.1.7 on 2023-03-02 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locais', '0004_bimby'),
        ('users', '0003_profile_bimby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bimby',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='locais.bimby'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='loja',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='locais.local'),
        ),
    ]
