# Generated by Django 4.1.7 on 2023-03-03 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locais', '0004_bimby'),
        ('users', '0005_alter_profile_first_name_alter_profile_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='aceito',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='bimby',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='loja',
        ),
        migrations.AddField(
            model_name='user',
            name='aceito',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='bimby',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='locais.bimby'),
        ),
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(default=' ', max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(default=' ', max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='loja',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='locais.local'),
        ),
    ]
